version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: cbtis239-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cbtis239
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: cbtis239-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  dbdata:
